### ISSUE TITLE
Updates to the wiki

### ISSUE THREAD

**Issue by morrilet** [Terasology/TutorialWorldGeneration#9]
I've gone ahead and made some updates to the current wiki pages to bring them more in line with the current example code. I made changes to the following pages:
- Additional Facet Production
- Borders
- Facet Configuration
- Facet Modification
- Facet Production
- Noise Sampling
- Rasterizer

Many of these changes were minor, but a couple snippets were pretty outdated.
All of my changes can be found [here](https://github.com/morrilet/TutorialWorldGenerationWiki).

**Comment by syntaxi** [comment]
Thanks for these updates. Outdated doc is definitely something that plagues us so we appreciate the fix ups.
I've added these to the wiki.
